### ISSUE TITLE
Using two or more triggers

### ISSUE THREAD

**Issue by vinikey** [CodyHouse/cd-drop-menu-changelog#2]
Hello CodyHouse team.

This is not an issue, it's more a help need / request. (I don't know how to label it)
I would like to have more than one trigger for the same drop-menu. The reason is that I could have buttons in different places (on mobile or desktop layout) using the same drop-menu. In this way I could have a unique source of menu.
As I can see in _3_drop-menu.js you get the trigger using querySelector. Since this returns only the first element, the events are assigned to the first element.
To override this, should I modify the js file and get all the aria-controls and loop them? Or there is a better way?

Thank you for your time.

**Comment by claudia-romano** [comment]
Hi there,
yes an option would be to use querySelectorAll to retrieve all the triggers and loop them to register the click events.
