### ISSUE TITLE
Allow buttons to act as links

### ISSUE THREAD

**Issue by melenaos** [CodyHouse/cd-drop-menu-changelog#3]
It's not always beneficial to use `a` elements as list items, for example, when you want to make an action without navigating to another page.

Using href="#0" is not a good solution since it messes with the browser history and the URL address.

It would be helpful to support a button with the `drop-menu__link` class.

```
<li><a class="drop-menu__link" href="#0">All Books</a></li>
<li><button class="drop-menu__link" click='alert("Children's Books")'>Children's Books</button></li>
<li><button class="drop-menu__link" click='alert("Crime & Mistery")'>Crime &amp; Mistery</button></li>
```

Currently, I am using a `span` but this is not a focusable element so the function `focusFirstElement` will fail.

**Comment by claudia-romano** [comment]
Hi Melenaos, we use href="#0" as a placeholder; users can replace them with their production urls. 

For your project, you can replace the anchor with a button tag. Are you having any issues with that? Thanks!

**Comment by melenaos** [comment]
Hi,
I have made a custom css rule for my project, so the button looks like the 'a' element.
I just writing to you incase you want to polish it for everybody else.
![image](https://user-images.githubusercontent.com/7249160/218333393-6967001b-22b5-4804-809d-dfcedfe76b49.png)

```
<li><a class="drop-menu__link" href="#0">Link with A element</a></li>
<li><button class="drop-menu__link" href="#0">Button</button></li>
<li><button class="btn" href="#0">Button without drop-menu__link</button></li>
<li><button class="btn width-100%" href="#0">Button width-100</button></li>
```

[Test project for drop-menu with buttons](https://github.com/melenaos/codyhouse-test)

**Comment by claudia-romano** [comment]
Thanks for clarifying that. Did you try the ```drop-menu__btn``` class?

**Comment by melenaos** [comment]
That looks great, no need for anything else. I am sorry that I haven't thought of that.

`<li><button class="reset drop-menu__btn">reset drop-menu__btn</button></li>`
